# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MatomoGf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MatomoGf
  pod 'MatomoTracker', '~> 7.5.2'

end
